### PR TITLE
fixing the names

### PR DESCRIPTION
**Pull request by Istabraq-Hussain**
changing names to lower case, and adding camel_case

### CODE REVIEW

**Comment by HoangGiang93** [comment]
Please merge my fixes, we will discuss afterwards
https://github.com/Multiverse-Framework/MultiverseVR/tree/IstaAssignment

**Comment by Istabraq-Hussain** [comment]
fixed naming convention

**Comment by HoangGiang93** [comment]
I just opened your level and saw no changes, did you push it?

https://github.com/Multiverse-Framework/MultiverseVR/assets/64316740/e8e315a9-315e-4116-a7be-3f287e1a001c

**Comment by HoangGiang93** [comment]
ah I see, you should make a PR not to main branch, but to IstaAssignment branch

**Pull request merged**
